server:
  port: 8080
spring:
  application:
    name: shiyu-gateway
  datasource:
    #  MySQL5用的驱动url是com.mysql.jdbc.Driver，MySQL6以后用的是com.mysql.cj.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.31.204:3306/shiyu
    username: root
    password: root

mybatis:
  mapper-locations: classpath:mapper/*.xml
  #目的是为了省略resultType里的代码量
  type-aliases-package: com.shiyu.cloud.user.bean
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
